name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.9.1
      - name: Build
        run: |
          yarn install
          yarn tsc
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Build
