name: Prettier
on: [push, pull_request]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.11.1
      - name: Prettier
        run: |
          yarn install
          yarn prettier . -w
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Format
